services:
  examination:
    image: ghcr.io/phamthanhlong100504-xpnd/examination:latest
    container_name: examination
    restart: unless-stopped
    ports: ["8082:8080"]
    mem_limit: 200m
    environment:
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx128m -Xquickstart"
      SPRING_DATASOURCE_URL: jdbc:postgresql://dts-postgres:5432/examination
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: dts-kafka:9092
    networks: [dts-network]

networks:
  dts-network: { external: true }
