services:
  examination:
    image: ghcr.io/phamthanhlong100504-xpnd/examination:latest
    container_name: examination
    restart: unless-stopped
    ports: ["8088:8088"]
    mem_limit: 275m
    environment:
      JAVA_TOOL_OPTIONS: "-Xms64m -Xmx128m -XX:+UseSerialGC -XX:MaxMetaspaceSize=128m -Xss256k"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/examination
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: "K59Ptl*100504"
      EUREKA_URI: "http://eureka-server:8761/eureka/"
      KAFKA_BOOTSTRAP_SERVERS: "hoangcn.com:9092"
    networks: [dts-network]

networks:
  dts-network: { external: true }
