spring:
  application:
    name: examination
  main:
    lazy-initialization: true
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://103.75.182.249:5434/examination
    username: postgres
    password: K59Ptl*100504
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  tomcat:
    threads:
      max: 50

jwt:
  # Secret key đã encode base64, dài > 256bit
  secret: uPq3xK8mR5vY2wZ9aB4cD7eF1gH3iJ6kL0nO5pQ8rS2tU4vW6xY9zA1bC3dE7fG9
